

# Eevee = {
#     "nome": "Eevee",
#     "raridade": "Incomum",
#     "dificuldade": 4,
#     "code": 29,
#     "tipo": ["normal"],
#     "evolução": Vaporeon,
#     "FF": None,
#     "vida": 69,
#     "atk": 22,
#     "atk SP": 14,
#     "def": 16,
#     "def SP": 22,
#     "velocidade": 25,
#     "XP": 40,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.2,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Porygon = {
#     "nome": "Porygon",
#     "raridade": "Comum",
#     "dificuldade": 2,
#     "code": 30,
#     "tipo": ["normal"],
#     "evolução": Porygon_2,
#     "FF": None,
#     "vida": 83,
#     "atk": 18,
#     "atk SP": 24,
#     "def": 23,
#     "def SP": 25,
#     "velocidade": 16,
#     "XP": 30,
#     "custo": 2,
#     "moves": 2,
#     "Tamanho": 1.4,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Scither = {
#     "nome": "Scither",
#     "raridade": "Epico",
#     "dificuldade": 8,
#     "code": 31,
#     "tipo": ["inseto", "voador"],
#     "evolução": Scizor,
#     "FF": None,
#     "vida": 104,
#     "atk": 49,
#     "atk SP": 20,
#     "def": 28,
#     "def SP": 26,
#     "velocidade": 45,
#     "XP": 45,
#     "custo": 1,
#     "moves": 3,
#     "Tamanho": 1.7,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Onix = {
#     "nome": "Onix",
#     "raridade": "Epico",
#     "dificuldade": 8,
#     "code": 32,
#     "tipo": ["pedra", "terrestre"],
#     "evolução": Steelix,
#     "FF": None,
#     "vida": 113,
#     "atk": 25,
#     "atk SP": 13,
#     "def": 57,
#     "def SP": 26,
#     "velocidade": 31,
#     "XP": 45,
#     "custo": 3,
#     "moves": 3,
#     "Tamanho": 2.7,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Chansey = {
#     "nome": "Chansey",
#     "raridade": "Raro",
#     "dificuldade": 6,
#     "code": 33,
#     "tipo": ["normal"],
#     "evolução": Blissey,
#     "FF": None,
#     "vida": 260,
#     "atk": 7,
#     "atk SP": 17,
#     "def": 10,
#     "def SP": 29,
#     "velocidade": 15,
#     "XP": 50,
#     "custo": 3,
#     "moves": 3,
#     "Tamanho": 1.7,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Mew = {
#     "nome": "Mew",
#     "tipo": ["psiquico"],
#     "evolução": None,
#     "FF": None,
#     "vida": 138,
#     "atk": 46,
#     "atk SP": 46,
#     "def": 46,
#     "def SP": 46,
#     "velocidade": 46,
#     "XP": 0,
#     "custo": 1,
#     "moves": 4,
#     "Tamanho": 1.2,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Koffing = {
#     "nome": "Koffing",
#     "raridade": "Incomum",
#     "dificuldade": 4,
#     "code": 35,
#     "tipo": ["venenoso"],
#     "evolução": Weezing,
#     "FF": None,
#     "vida": 79,
#     "atk": 19,
#     "atk SP": 20,
#     "def": 26,
#     "def SP": 17,
#     "velocidade": 23,
#     "XP": 40,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.2,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Ditto = {
#     "nome": "Ditto",
#     "raridade": "Incomum",
#     "dificuldade": 4,
#     "code": 36,
#     "tipo": ["normal"],
#     "evolução": None,
#     "FF": None,
#     "vida": 54,
#     "atk": 18,
#     "atk SP": 18,
#     "def": 18,
#     "def SP": 18,
#     "velocidade": 18,
#     "XP": 0,
#     "custo": 1,
#     "moves": 1,
#     "Tamanho": 1.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Mr_Mime = {
#     "nome": "Mr Mime",
#     "raridade": "Raro",
#     "dificuldade": 6,
#     "code": 37,
#     "tipo": ["psiquico", "fada"],
#     "evolução": None,
#     "FF": None,
#     "vida": 101,
#     "atk": 18,
#     "atk SP": 27,
#     "def": 22,
#     "def SP": 39,
#     "velocidade": 29,
#     "XP": 0,
#     "custo": 2,
#     "moves": 4,
#     "Tamanho": 1.5,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Grimer = {
#     "nome": "Grimer",
#     "raridade": "Incomum",
#     "dificuldade": 4,
#     "code": 38,
#     "tipo": ["venenoso"],
#     "evolução": Muk,
#     "FF": None,
#     "vida": 100,
#     "atk": 31,
#     "atk SP": 22,
#     "def": 21,
#     "def SP": 21,
#     "velocidade": 13,
#     "XP": 40,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.4,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Growlithe = {
#     "nome": "Growlithe",
#     "raridade": "Incomum",
#     "dificuldade": 4,
#     "code": 39,
#     "tipo": ["fogo"],
#     "evolução": Arcanine,
#     "FF": None,
#     "vida": 91,
#     "atk": 27,
#     "atk SP": 25,
#     "def": 20,
#     "def SP": 19,
#     "velocidade": 24,
#     "XP": 45,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.4,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Hitmonlee = {
#     "nome": "Hitmonlee",
#     "raridade": "Raro",
#     "dificuldade": 6,
#     "code": 40,
#     "tipo": ["lutador"],
#     "evolução": None,
#     "FF": None,
#     "vida": 118,
#     "atk": 37,
#     "atk SP": 16,
#     "def": 29,
#     "def SP": 36,
#     "velocidade": 26,
#     "XP": 0,
#     "custo": 2,
#     "moves": 4,
#     "Tamanho": 1.5,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Hitmonchan = {
#     "nome": "Hitmonchan",
#     "raridade": "Raro",
#     "dificuldade": 6,
#     "code": 41,
#     "tipo": ["lutador"],
#     "evolução": None,
#     "FF": None,
#     "vida": 113,
#     "atk": 39,
#     "atk SP": 17,
#     "def": 24,
#     "def SP": 32,
#     "velocidade": 34,
#     "XP": 0,
#     "custo": 2,
#     "moves": 4,
#     "Tamanho": 1.5,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Exegute = {
#     "nome": "Exegute",
#     "raridade": "Comum",
#     "dificuldade": 2,
#     "code": 42,
#     "tipo": ["planta", "psiquico"],
#     "evolução": Exeggutor,
#     "FF": None,
#     "vida": 55,
#     "atk": 16,
#     "atk SP": 15,
#     "def": 18,
#     "def SP": 21,
#     "velocidade": 21,
#     "XP": 50,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Beelsprount = {
#     "nome": "Beelsprount",
#     "raridade": "Incomum",
#     "dificuldade": 4,
#     "code": 43,
#     "tipo": ["planta", "venenoso"],
#     "evolução": Weepimbell,
#     "FF": None,
#     "vida": 60,
#     "atk": 26,
#     "atk SP": 26,
#     "def": 18,
#     "def SP": 17,
#     "velocidade": 19,
#     "XP": 25,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.2,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Poliwag = {
#     "nome": "Poliwag",
#     "raridade": "Incomum",
#     "dificuldade": 4,
#     "code": 44,
#     "tipo": ["agua"],
#     "evolução": Poliwhirl,
#     "FF": None,
#     "vida": 68,
#     "atk": 22,
#     "atk SP": 19,
#     "def": 14,
#     "def SP": 16,
#     "velocidade": 33,
#     "XP": 25,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Celebi = {
#     "nome": "Celebi",
#     "tipo": ["psiquico", "planta"],
#     "evolução": None,
#     "FF": None,
#     "vida": 124,
#     "atk": 50,
#     "atk SP": 50,
#     "def": 35,
#     "def SP": 35,
#     "velocidade": 43,
#     "XP": 0,
#     "custo": 1,
#     "moves": 4,
#     "Tamanho": 1.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Suicune = {
#     "nome": "Suicune",
#     "tipo": ["agua"],
#     "evolução": None,
#     "FF": None,
#     "vida": 176,
#     "atk": 38,
#     "atk SP": 66,
#     "def": 54,
#     "def SP": 60,
#     "velocidade": 48,
#     "XP": 0,
#     "custo": 2,
#     "moves": 4,
#     "Tamanho": 1.8,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Entei = {
#     "nome": "Entei",
#     "tipo": ["fogo"],
#     "evolução": None,
#     "FF": None,
#     "vida": 219,
#     "atk": 70,
#     "atk SP": 40,
#     "def": 50,
#     "def SP": 49,
#     "velocidade": 45,
#     "XP": 0,
#     "custo": 3,
#     "moves": 4,
#     "Tamanho": 2.0,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Raikou = {
#     "nome": "Raikou",
#     "tipo": ["eletrico"],
#     "evolução": None,
#     "FF": None,
#     "vida": 170,
#     "atk": 50,
#     "atk SP": 66,
#     "def": 42,
#     "def SP": 48,
#     "velocidade": 69,
#     "XP": 0,
#     "custo": 2,
#     "moves": 4,
#     "Tamanho": 1.8,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Lugia = {
#     "nome": "Lugia",
#     "tipo": ["psiquico", "voador"],
#     "evolução": None,
#     "FF": None,
#     "vida": 242,
#     "atk": 39,
#     "atk SP": 53,
#     "def": 56,
#     "def SP": 92,
#     "velocidade": 49,
#     "XP": 0,
#     "custo": 4,
#     "moves": 4,
#     "Tamanho": 2.9,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Larvitar = {
#     "nome": "Larvitar",
#     "raridade": "Raro",
#     "dificuldade": 6,
#     "code": 50,
#     "tipo": ["pedra", "terrestre"],
#     "evolução": Pupitar,
#     "FF": None,
#     "vida": 85,
#     "atk": 23,
#     "atk SP": 16,
#     "def": 22,
#     "def SP": 22,
#     "velocidade": 18,
#     "XP": 30,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.2,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Mareep = {
#     "nome": "Mareep",
#     "raridade": "Incomum",
#     "dificuldade": 4,
#     "code": 51,
#     "tipo": ["eletrico"],
#     "evolução": Flaaffy,
#     "FF": None,
#     "vida": 89,
#     "atk": 15,
#     "atk SP": 22,
#     "def": 19,
#     "def SP": 18,
#     "velocidade": 17,
#     "XP": 25,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.3,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Marril = {
#     "nome": "Marril",
#     "raridade": "Comum",
#     "dificuldade": 2,
#     "code": 52,
#     "tipo": ["agua", "fada"],
#     "evolução": Azumarill,
#     "FF": None,
#     "vida": 90,
#     "atk": 2,
#     "atk SP": 10,
#     "def": 22,
#     "def SP": 23,
#     "velocidade": 18,
#     "XP": 30,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Shuckle = {
#     "nome": "Shuckle",
#     "raridade": "Raro",
#     "dificuldade": 6,
#     "code": 53,
#     "tipo": ["inseto", "pedra"],
#     "evolução": None,
#     "FF": None,
#     "vida": 54,
#     "atk": 8,
#     "atk SP": 8,
#     "def": 75,
#     "def SP": 75,
#     "velocidade": 7,
#     "XP": 0,
#     "custo": 2,
#     "moves": 4,
#     "Tamanho": 1.3,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Wabufeet = {
#     "nome": "Wabufeet",
#     "raridade": "Raro",
#     "dificuldade": 6,
#     "code": 54,
#     "tipo": ["psiquico"],
#     "evolução": None,
#     "FF": None,
#     "vida": 199,
#     "atk": 16,
#     "atk SP": 14,
#     "def": 22,
#     "def SP": 23,
#     "velocidade": 13,
#     "XP": 0,
#     "custo": 2,
#     "moves": 4,
#     "Tamanho": 1.4,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Torchic = {
#     "nome": "Torchic",
#     "raridade": "Incomum",
#     "dificuldade": 4,
#     "code": 55,
#     "tipo": ["fogo"],
#     "evolução": Combusken,
#     "FF": None,
#     "vida": 65,
#     "atk": 22,
#     "atk SP": 24,
#     "def": 17,
#     "def SP": 18,
#     "velocidade": 20,
#     "XP": 25,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Treeko = {
#     "nome": "Treeko",
#     "raridade": "Incomum",
#     "dificuldade": 4,
#     "code": 56,
#     "tipo": ["planta"],
#     "evolução": Grovyle,
#     "FF": None,
#     "vida": 62,
#     "atk": 17,
#     "atk SP": 22,
#     "def": 18,
#     "def SP": 21,
#     "velocidade": 26,
#     "XP": 25,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Mudkip = {
#     "nome": "Mudkip",
#     "raridade": "Incomum",
#     "dificuldade": 4,
#     "code": 57,
#     "tipo": ["agua"],
#     "evolução": Marshtomp,
#     "FF": None,
#     "vida": 70,
#     "atk": 25,
#     "atk SP": 16,
#     "def": 20,
#     "def SP": 19,
#     "velocidade": 19,
#     "XP": 25,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Lotad = {
#     "nome": "Lotad",
#     "raridade": "Comum",
#     "dificuldade": 2,
#     "code": 58,
#     "tipo": ["agua", "planta"],
#     "evolução": Lombre,
#     "FF": None,
#     "vida": 82,
#     "atk": 16,
#     "atk SP": 14,
#     "def": 19,
#     "def SP": 24,
#     "velocidade": 14,
#     "XP": 20,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.4,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Seedot = {
#     "nome": "Seedot",
#     "raridade": "Comum",
#     "dificuldade": 2,
#     "code": 59,
#     "tipo": ["planta"],
#     "evolução": Nuzleaf,
#     "FF": None,
#     "vida": 35,
#     "atk": 18,
#     "atk SP": 12,
#     "def": 27,
#     "def SP": 19,
#     "velocidade": 17,
#     "XP": 20,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.0,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Ralts = {
#     "nome": "Ralts",
#     "raridade": "Incomum",
#     "dificuldade": 4,
#     "code": 60,
#     "tipo": ["psiquico", "fada"],
#     "evolução": Kirlia,
#     "FF": None,
#     "vida": 41,
#     "atk": 14,
#     "atk SP": 25,
#     "def": 14,
#     "def SP": 24,
#     "velocidade": 17,
#     "XP": 25,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Wurple = {
#     "nome": "Wurple",
#     "raridade": "Comum",
#     "dificuldade": 2,
#     "code": 61,
#     "tipo": ["inseto"],
#     "evolução": Cascoon,
#     "FF": None,
#     "vida": 63,
#     "atk": 18,
#     "atk SP": 15,
#     "def": 21,
#     "def SP": 22,
#     "velocidade": 6,
#     "XP": 20,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Sableye = {
#     "nome": "Sableye",
#     "raridade": "Raro",
#     "dificuldade": 6,
#     "code": 62,
#     "tipo": ["sombrio", "fantasma"],
#     "evolução": Mega Sableye,
#     "FF": None,
#     "vida": 75,
#     "atk": 34,
#     "atk SP": 24,
#     "def": 31,
#     "def SP": 28,
#     "velocidade": 27,
#     "XP": 35,
#     "custo": 1,
#     "moves": 4,
#     "Tamanho": 1.3,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Aron = {
#     "nome": "Aron",
#     "raridade": "Raro",
#     "dificuldade": 6,
#     "code": 63,
#     "tipo": ["metal", "pedra"],
#     "evolução": Lairon,
#     "FF": None,
#     "vida": 82,
#     "atk": 23,
#     "atk SP": 12,
#     "def": 30,
#     "def SP": 17,
#     "velocidade": 17,
#     "XP": 30,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.2,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Wailmer = {
#     "nome": "Wailmer",
#     "raridade": "Epico",
#     "dificuldade": 8,
#     "code": 64,
#     "tipo": ["agua"],
#     "evolução": Wailord,
#     "FF": None,
#     "vida": 182,
#     "atk": 24,
#     "atk SP": 24,
#     "def": 17,
#     "def SP": 16,
#     "velocidade": 25,
#     "XP": 50,
#     "custo": 3,
#     "moves": 3,
#     "Tamanho": 2.0,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Cacnea = {
#     "nome": "Cacnea",
#     "raridade": "Incomum",
#     "dificuldade": 4,
#     "code": 65,
#     "tipo": ["planta"],
#     "evolução": Cacturne,
#     "FF": None,
#     "vida": 67,
#     "atk": 27,
#     "atk SP": 27,
#     "def": 19,
#     "def SP": 19,
#     "velocidade": 16,
#     "XP": 35,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Lunatone = {
#     "nome": "Lunatone",
#     "raridade": "Raro",
#     "dificuldade": 6,
#     "code": 66,
#     "tipo": ["pedra", "psiquico"],
#     "evolução": None,
#     "FF": None,
#     "vida": 103,
#     "atk": 21,
#     "atk SP": 35,
#     "def": 21,
#     "def SP": 35,
#     "velocidade": 23,
#     "XP": 0,
#     "custo": 1,
#     "moves": 4,
#     "Tamanho": 1.3,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Solrock = {
#     "nome": "Solrock",
#     "raridade": "Raro",
#     "dificuldade": 6,
#     "code": 67,
#     "tipo": ["pedra", "psiquico"],
#     "evolução": None,
#     "FF": None,
#     "vida": 103,
#     "atk": 34,
#     "atk SP": 22,
#     "def": 34,
#     "def SP": 22,
#     "velocidade": 23,
#     "XP": 0,
#     "custo": 1,
#     "moves": 4,
#     "Tamanho": 1.3,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Shuppet = {
#     "nome": "Shuppet",
#     "raridade": "Comum",
#     "dificuldade": 2,
#     "code": 68,
#     "tipo": ["fantasma"],
#     "evolução": Bannete,
#     "FF": None,
#     "vida": 48,
#     "atk": 26,
#     "atk SP": 24,
#     "def": 14,
#     "def SP": 11,
#     "velocidade": 28,
#     "XP": 40,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.0,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Absol = {
#     "nome": "Absol",
#     "raridade": "Epico",
#     "dificuldade": 8,
#     "code": 69,
#     "tipo": ["sombrio"],
#     "evolução": Mega Absol,
#     "FF": None,
#     "vida": 115,
#     "atk": 69,
#     "atk SP": 34,
#     "def": 24,
#     "def SP": 26,
#     "velocidade": 38,
#     "XP": 45,
#     "custo": 2,
#     "moves": 4,
#     "Tamanho": 1.6,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Snorunt = {
#     "nome": "Snorunt",
#     "raridade": "Incomum",
#     "dificuldade": 4,
#     "code": 70,
#     "tipo": ["gelo"],
#     "evolução": Glalie,
#     "FF": None,
#     "vida": 63,
#     "atk": 21,
#     "atk SP": 21,
#     "def": 21,
#     "def SP": 21,
#     "velocidade": 21,
#     "XP": 45,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.2,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Beldum = {
#     "nome": "Beldum",
#     "raridade": "Raro",
#     "dificuldade": 6,
#     "code": 71,
#     "tipo": ["metal", "psiquico"],
#     "evolução": Metang,
#     "FF": None,
#     "vida": 65,
#     "atk": 21,
#     "atk SP": 15,
#     "def": 28,
#     "def SP": 25,
#     "velocidade": 19,
#     "XP": 30,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Swablu = {
#     "nome": "Swablu",
#     "raridade": "Raro",
#     "dificuldade": 6,
#     "code": 72,
#     "tipo": ["normal", "voador"],
#     "evolução": Altaria,
#     "FF": None,
#     "vida": 67,
#     "atk": 18,
#     "atk SP": 18,
#     "def": 26,
#     "def SP": 29,
#     "velocidade": 25,
#     "XP": 50,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.3,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Bagon = {
#     "nome": "Bagon",
#     "raridade": "Raro",
#     "dificuldade": 6,
#     "code": 73,
#     "tipo": ["dragao"],
#     "evolução": Shelgon,
#     "FF": None,
#     "vida": 74,
#     "atk": 29,
#     "atk SP": 21,
#     "def": 23,
#     "def SP": 13,
#     "velocidade": 19,
#     "XP": 30,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.2,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Regirock = {
#     "nome": "Regirock",
#     "tipo": ["pedra"],
#     "evolução": None,
#     "FF": None,
#     "vida": 168,
#     "atk": 48,
#     "atk SP": 30,
#     "def": 82,
#     "def SP": 46,
#     "velocidade": 27,
#     "XP": 0,
#     "custo": 4,
#     "moves": 4,
#     "Tamanho": 2.2,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Regice = {
#     "nome": "Regice",
#     "tipo": ["gelo"],
#     "evolução": None,
#     "FF": None,
#     "vida": 168,
#     "atk": 30,
#     "atk SP": 48,
#     "def": 46,
#     "def SP": 82,
#     "velocidade": 27,
#     "XP": 0,
#     "custo": 4,
#     "moves": 4,
#     "Tamanho": 2.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Registeel = {
#     "nome": "Registeel",
#     "tipo": ["metal"],
#     "evolução": None,
#     "FF": None,
#     "vida": 168,
#     "atk": 39,
#     "atk SP": 39,
#     "def": 64,
#     "def SP": 64,
#     "velocidade": 27,
#     "XP": 0,
#     "custo": 4,
#     "moves": 4,
#     "Tamanho": 2.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Latias = {
#     "nome": "Latias",
#     "tipo": ["dragao", "psiquico"],
#     "evolução": Mega Latias,
#     "FF": None,
#     "vida": 149,
#     "atk": 34,
#     "atk SP": 42,
#     "def": 45,
#     "def SP": 61,
#     "velocidade": 65,
#     "XP": 35,
#     "custo": 2,
#     "moves": 4,
#     "Tamanho": 1.8,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Latios = {
#     "nome": "Latios",
#     "tipo": ["dragao", "psiquico"],
#     "evolução": Mega Latios,
#     "FF": None,
#     "vida": 149,
#     "atk": 45,
#     "atk SP": 61,
#     "def": 34,
#     "def SP": 42,
#     "velocidade": 65,
#     "XP": 35,
#     "custo": 2,
#     "moves": 4,
#     "Tamanho": 1.8,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Kyogre = {
#     "nome": "Kyogre",
#     "tipo": ["agua"],
#     "evolução": Mega Kyogre,
#     "FF": None,
#     "vida": 236,
#     "atk": 48,
#     "atk SP": 79,
#     "def": 58,
#     "def SP": 75,
#     "velocidade": 37,
#     "XP": 45,
#     "custo": 4,
#     "moves": 4,
#     "Tamanho": 3.0,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Groundon = {
#     "nome": "Groundon",
#     "tipo": ["terrestre"],
#     "evolução": Mega Groundon,
#     "FF": None,
#     "vida": 236,
#     "atk": 79,
#     "atk SP": 48,
#     "def": 75,
#     "def SP": 58,
#     "velocidade": 37,
#     "XP": 45,
#     "custo": 4,
#     "moves": 4,
#     "Tamanho": 3.0,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Rayquaza = {
#     "nome": "Rayquaza",
#     "tipo": ["dragao", "voador"],
#     "evolução": Mega Rayquaza,
#     "FF": None,
#     "vida": 204,
#     "atk": 72,
#     "atk SP": 72,
#     "def": 52,
#     "def SP": 52,
#     "velocidade": 76,
#     "XP": 45,
#     "custo": 3,
#     "moves": 4,
#     "Tamanho": 3.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Jirachi = {
#     "nome": "Jirachi",
#     "tipo": ["metal", "psiquico"],
#     "evolução": None,
#     "FF": None,
#     "vida": 124,
#     "atk": 35,
#     "atk SP": 35,
#     "def": 50,
#     "def SP": 50,
#     "velocidade": 43,
#     "XP": 0,
#     "custo": 1,
#     "moves": 4,
#     "Tamanho": 1.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Togepi = {
#     "nome": "Togepi",
#     "raridade": "Incomum",
#     "dificuldade": 4,
#     "code": 83,
#     "tipo": ["fada"],
#     "evolução": Togetic,
#     "FF": None,
#     "vida": 40,
#     "atk": 8,
#     "atk SP": 17,
#     "def": 27,
#     "def SP": 27,
#     "velocidade": 9,
#     "XP": 25,
#     "custo": 1,
#     "moves": 2,
#     "Tamanho": 1.1,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Deoxys = {
#     "nome": "Deoxys",
#     "tipo": ["psiquico"],
#     "evolução": None,
#     "FF": None,
#     "vida": 100,
#     "atk": 55,
#     "atk SP": 55,
#     "def": 54,
#     "def SP": 54,
#     "velocidade": 58,
#     "XP": 0,
#     "custo": 2,
#     "moves": 4,
#     "Tamanho": 1.5,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Deoxys_Speed = {
#     "nome": "Deoxys Speed",
#     "tipo": ["psiquico"],
#     "evolução": None,
#     "FF": None,
#     "vida": 100,
#     "atk": 48,
#     "atk SP": 48,
#     "def": 47,
#     "def SP": 47,
#     "velocidade": 95,
#     "XP": 0,
#     "custo": 2,
#     "moves": 4,
#     "Tamanho": 1.5,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Deoxys_Attack = {
#     "nome": "Deoxys Attack",
#     "tipo": ["psiquico"],
#     "evolução": None,
#     "FF": None,
#     "vida": 100,
#     "atk": 88,
#     "atk SP": 88,
#     "def": 20,
#     "def SP": 20,
#     "velocidade": 56,
#     "XP": 0,
#     "custo": 2,
#     "moves": 4,
#     "Tamanho": 1.5,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }

# Deoxys_Defense = {
#     "nome": "Deoxys Defense",
#     "tipo": ["psiquico"],
#     "evolução": None,
#     "FF": None,
#     "vida": 100,
#     "atk": 36,
#     "atk SP": 36,
#     "def": 78,
#     "def SP": 78,
#     "velocidade": 38,
#     "XP": 0,
#     "custo": 2,
#     "moves": 4,
#     "Tamanho": 1.5,
#     "movelist": [],
#     "H": 0,
#     "W": 0
# }
