from Dados.Gen1.V import Snorlax_V,Meowth_V,Pikachu_V
from Dados.Gen1.Mega import Mega_Aerodactyl,Mega_Pinsir,Mega_Mewtwo_X,Mega_Mewtwo_Y
from Dados.Gen1.Evo1 import Ivysaur,Charmeleon,Wartortle,Machoke,Haunter,Graveler,Metapod,Kadabra,Dragonair,Raichu,Zoroark,Gyarados,Wigglytuff,Magneton,Raticate,Kakuna,Clefable,Persian,Marowak,Cloyster

Bulbasaur = {
    "nome": "Bulbasaur",
    "raridade": "Incomum",
    "dificuldade": 4,
    "code": 1,
    "tipo": ["planta", "venenoso"],
    "evolução": Ivysaur,
    "FF": None,
    "vida": 74,
    "atk": 17,
    "atk SP": 24,
    "def": 15,
    "def SP": 22,
    "velocidade": 22,
    "XP": 25,
    "custo": 1,
    "moves": 4,
    "Tamanho": 1.3,
    "movelist": ["Controle do Oceano", "Vento Forte", "Mão Espectral", "Tremor", "Quebra Chão", "Crescer"],
    "H": 0.58,
    "W": 7.5
}

Charmander = {
    "nome": "Charmander",
    "raridade": "Incomum",
    "dificuldade": 4,
    "code": 2,
    "tipo": ["fogo"],
    "evolução": Charmeleon,
    "FF": None,
    "vida": 70,
    "atk": 21,
    "atk SP": 23,
    "def": 16,
    "def SP": 18,
    "velocidade": 24,
    "XP": 25,
    "custo": 1,
    "moves": 2,
    "Tamanho": 1.3,
    "movelist": ["Tapa", "Queimar", "Superaquecer", "Mordida", "Crescer", "Brasa"],
    "H": 0.7,   
    "W": 8.5
}

Squirtle = {
    "nome": "Squirtle",
    "raridade": "Incomum",
    "dificuldade": 4,
    "code": 3,
    "tipo": ["agua"],
    "evolução": Wartortle,
    "FF": None,
    "vida": 72,
    "atk": 19,
    "atk SP": 16,
    "def": 23,
    "def SP": 22,
    "velocidade": 20,
    "XP": 25,
    "custo": 1,
    "moves": 2,
    "Tamanho": 1.3,
    "movelist": ["Investida", "Jato de Água", "Bolhas", "Vasculhar no Rio", "Provocar", "Crescer"],
    "H": 0.67,
    "W": 10
}

Machop = {
    "nome": "Machop",
    "raridade": "Incomum",
    "dificuldade": 4,
    "code": 4,
    "tipo": ["lutador"],
    "evolução": Machoke,
    "FF": None,
    "vida": 89,
    "atk": 24,
    "atk SP": 15,
    "def": 23,
    "def SP": 20,
    "velocidade": 20,
    "XP": 25,
    "custo": 2,
    "moves": 2,
    "Tamanho": 1.4,
    "movelist": ["Treinar", "Soco", "Provocar", "Pedregulho", "Crescer", "Tapa Especial"],
    "H": 0.9,
    "W": 20
}

Gastly = {
    "nome": "Gastly",
    "raridade": "Incomum",
    "dificuldade": 4,
    "code": 5,
    "tipo": ["fantasma", "venenoso"],
    "evolução": Haunter,
    "FF": None,
    "vida": 60,
    "atk": 15,
    "atk SP": 26,
    "def": 15,
    "def SP": 18,
    "velocidade": 25,
    "XP": 25,
    "custo": 0,
    "moves": 2,
    "Tamanho": 1.2,
    "movelist": ["Lambida", "Ácido", "Envenenar", "Assombrar", "Energia", "Atravessar"],
    "H": 0.6,
    "W": 0.2
}

Geodude = {
    "nome": "Geodude",
    "raridade": "Incomum",
    "dificuldade": 4,
    "code": 6,
    "tipo": ["pedra", "terrestre"],
    "evolução": Graveler,
    "FF": None,
    "vida": 81,
    "atk": 22,
    "atk SP": 17,
    "def": 26,
    "def SP": 22,
    "velocidade": 17,
    "XP": 25,
    "custo": 2,
    "moves": 2,
    "Tamanho": 1.2,
    "movelist": ["Soco", "Pedregulho", "Provocar", "Investida", "Esbravejar", "Tremor"],
    "H": 0.51,
    "W": 23
}

Caterpie = {
    "nome": "Caterpie",
    "raridade": "Comum",
    "dificuldade": 2,
    "code": 7,
    "tipo": ["inseto"],
    "evolução": Metapod,
    "FF": None,
    "vida": 61,
    "atk": 17,
    "atk SP": 19,
    "def": 16,
    "def SP": 18,
    "velocidade": 17,
    "XP": 20,
    "custo": 1,
    "moves": 2,
    "Tamanho": 1.0,
    "movelist": ["Seda", "Cabeçada", "Mordida", "Minhocagem", "Coleta", "Energia"],
    "H": 0.31,
    "W": 3.3
}

Abra = {
    "nome": "Abra",
    "raridade": "Incomum",
    "dificuldade": 4,
    "code": 8,
    "tipo": ["psiquico"],
    "evolução": Kadabra,
    "FF": None,
    "vida": 56,
    "atk": 14,
    "atk SP": 29,
    "def": 13,
    "def SP": 19,
    "velocidade": 24,
    "XP": 25,
    "custo": 0,
    "moves": 2,
    "Tamanho": 1.3,
    "movelist": ["Teleporte", "Ampliação Mental", "Confusão", "Psíquico Desgastante", "Tapa Especial", "Tapa"],
    "H": 1,
    "W": 20
}

Dratini = {
    "nome": "Dratini",
    "raridade": "Raro",
    "dificuldade": 6,
    "code": 9,
    "tipo": ["dragao"],
    "evolução": Dragonair,
    "FF": None,
    "vida": 81,
    "atk": 22,
    "atk SP": 18,
    "def": 21,
    "def SP": 21,
    "velocidade": 21,
    "XP": 30,
    "custo": 1,
    "moves": 2,
    "Tamanho": 1.3,
    "movelist": ["Ultraje", "Sopro do Dragão", "Cabeçada", "Mordida", "Crescer", "Bolhas"],
    "H": 1.81,
    "W": 3.4
}

Pikachu = {
    "nome": "Pikachu",
    "raridade": "Raro",
    "dificuldade": 6,
    "code": 10,
    "tipo": ["eletrico"],
    "evolução": Raichu,
    "FF": None,
    "vida": 90,
    "atk": 20,
    "atk SP": 28,
    "def": 22,
    "def SP": 20,
    "velocidade": 35,
    "XP": 40,
    "custo": 1,
    "moves": 3,
    "Tamanho": 1.4,
    "movelist": ["Cauda de Ferro", "Ataque Rápido", "Choque do Trovão", "Faisca", "Bola Elétrica", "Energizar"],
    "H": 0.51,
    "W": 6.3
}

Zorua = {
    "nome": "Zorua",
    "raridade": "Raro",
    "dificuldade": 6,
    "code": 11,
    "tipo": ["sombrio"],
    "evolução": Zoroark,
    "FF": None,
    "vida": 83,
    "atk": 23,
    "atk SP": 27,
    "def": 19,
    "def SP": 19,
    "velocidade": 29,
    "XP": 40,
    "custo": 1,
    "moves": 2,
    "Tamanho": 1.3,
    "movelist": ["Investida", "Nas Sombras", "Bola Sombria", "Vasculhar", "Energia", "Crescer"],
    "H": 0.68,
    "W": 10.2
}

Magikarp = {
    "nome": "Magikarp",
    "raridade": "Comum",
    "dificuldade": 2,
    "code": 12,
    "tipo": ["agua"],
    "evolução": Gyarados,
    "FF": None,
    "vida": 65,
    "atk": 9,
    "atk SP": 12,
    "def": 24,
    "def SP": 13,
    "velocidade": 28,
    "XP": 50,
    "custo": 1,
    "moves": 2,
    "Tamanho": 1.2,
    "movelist": ["Splash", "Vasculhar", "Vasculhar no Rio", "Splash", "Splash", "Splash"],
    "H": 0.85,
    "W": 9.1
}

Jigglypuff = {
    "nome": "Jigglypuff",
    "raridade": "Comum",
    "dificuldade": 2,
    "code": 13,
    "tipo": ["fada", "normal"],
    "evolução": Wigglytuff,
    "FF": None,
    "vida": 142,
    "atk": 22,
    "atk SP": 14,
    "def": 18,
    "def SP": 20,
    "velocidade": 18,
    "XP": 35,
    "custo": 1,
    "moves": 2,
    "Tamanho": 1.2,
    "movelist": ["Tapa", "Cura Natural", "Brilho", "Energia", "Busca Alegre", "Tapa Especial"],
    "H": 0.56,
    "W": 6.7
}

Clefairy = {
    "nome": "Clefairy",
    "raridade": "Comum",
    "dificuldade": 2,
    "code": 14,
    "tipo": ["fada"],
    "evolução": Clefable,
    "FF": None,
    "vida": 106,
    "atk": 16,
    "atk SP": 23,
    "def": 20,
    "def SP": 26,
    "velocidade": 14,
    "XP": 40,
    "custo": 2,
    "moves": 2,
    "Tamanho": 1.2,
    "movelist": ["Provocar", "Vento Fada", "Brilho", "Benção", "Investida", "Energia"],
    "H": 0.62,
    "W": 8.9
}

Meowth = {
    "nome": "Meowth",
    "raridade": "Comum",
    "dificuldade": 2,
    "code": 15,
    "tipo": ["normal"],
    "evolução": Persian,
    "FF": None,
    "vida": 78,
    "atk": 23,
    "atk SP": 19,
    "def": 18,
    "def SP": 18,
    "velocidade": 29,
    "XP": 35,
    "custo": 1,
    "moves": 2,
    "Tamanho": 1.3,
    "movelist": ["Tapa", "Tapa Especial", "Vasculhar", "Arranhar", "Crescer", "Coleta Gananciosa"],
    "H": 0.63,
    "W": 5.1
}

Cubone = {
    "nome": "Cubone",
    "raridade": "Incomum",
    "dificuldade": 4,
    "code": 16,
    "tipo": ["terrestre"],
    "evolução": Marowak,
    "FF": None,
    "vida": 79,
    "atk": 20,
    "atk SP": 18,
    "def": 27,
    "def SP": 22,
    "velocidade": 20,
    "XP": 35,
    "custo": 1,
    "moves": 2,
    "Tamanho": 1.2,
    "movelist": ["Provocar", "Pedregulho", "Soco", "Arremesso de Terra", "Tremor", "Crescer"],
    "H": 0.42,
    "W": 7.1

}

Shellder = {
    "nome": "Shellder",
    "raridade": "Incomum",
    "dificuldade": 4,
    "code": 17,
    "tipo": ["agua"],
    "evolução": Cloyster,
    "FF": None,
    "vida": 56,
    "atk": 24,
    "atk SP": 14,
    "def": 29,
    "def SP": 17,
    "velocidade": 21,
    "XP": 40,
    "custo": 1,
    "moves": 2,
    "Tamanho": 1.1,
    "movelist": ["Lambida", "Provocar", "Jato de Água", "Bolhas", "Energia", "Golpe de Concha"],
    "H": 0.33,
    "W": 4

}

Magnemite = {
    "nome": "Magnemite",
    "raridade": "Comum",
    "dificuldade": 2,
    "code": 18,
    "tipo": ["eletrico", "metal"],
    "evolução": Magneton,
    "FF": None,
    "vida": 40,
    "atk": 16,
    "atk SP": 26,
    "def": 25,
    "def SP": 22,
    "velocidade": 19,
    "XP": 25,
    "custo": 1,
    "moves": 2,
    "Tamanho": 1.0,
    "movelist": ["Reforçar", "Faisca", "Energia", "Energizar", "Projétil Metálico", "Onda Elétrica"],
    "H": 0.29,
    "W": 6.7

}

Rattata = {
    "nome": "Rattata",
    "raridade": "Comum",
    "dificuldade": 2,
    "code": 19,
    "tipo": ["normal"],
    "evolução": Raticate,
    "FF": None,
    "vida": 64,
    "atk": 20,
    "atk SP": 8,
    "def": 17,
    "def SP": 14,
    "velocidade": 27,
    "XP": 30,
    "custo": 0,
    "moves": 2,
    "Tamanho": 1.1,
    "movelist": ["Mordida", "Investida", "Nas Sombras", "Vasculhar", "Crescer", "Envenenar"],
    "H": 0.34,
    "W": 3.3
}

Weedle = {
    "nome": "Weedle",
    "raridade": "Comum",
    "dificuldade": 2,
    "code": 20,
    "tipo": ["inseto"],
    "evolução": Kakuna,
    "FF": None,
    "vida": 46,
    "atk": 20,
    "atk SP": 18,
    "def": 14,
    "def SP": 15,
    "velocidade": 19,
    "XP": 20,
    "custo": 1,
    "moves": 2,
    "Tamanho": 1.0,
    "movelist": ["Minhocagem", "Seda", "Picada", "Vasculhar", "Envenenar", "Coleta"],
    "H": 0.26,
    "W": 2.5
}

Snorlax = {
    "nome": "Snorlax",
    "raridade": "Epico",
    "dificuldade": 8,
    "code": 21,
    "tipo": ["normal"],
    "evolução": None,
    "FF": None,
    "vida": 245,
    "atk": 44,
    "atk SP": 30,
    "def": 31,
    "def SP": 35,
    "velocidade": 14,
    "XP": 0,
    "custo": 4,
    "moves": 4,
    "Tamanho": 2.6,
    "movelist": ["Arranhar", "Tapa", "Tapa Especial", "Provocar", "Esmagar", "Descansar"],
    "H": 2.15,
    "W": 485

}

Aerodactyl = {
    "nome": "Aerodactyl",
    "raridade": "Epico",
    "dificuldade": 8,
    "code": 22,
    "tipo": ["pedra", "voador"],
    "evolução": None,
    "FF": [Mega_Aerodactyl],
    "vida": 135,
    "atk": 45,
    "atk SP": 33,
    "def": 30,
    "def SP": 27,
    "velocidade": 50,
    "XP": 0,
    "custo": 3,
    "moves": 4,
    "Tamanho": 2.0,
    "movelist": ["Voar", "Ataque de Asa", "Investida Aérea", "Pedra Especial", "Barragem Rochosa", "Mordida"],
    "H": 1.8,
    "W": 60

}

Jynx = {
    "nome": "Jynx",
    "raridade": "Raro",
    "dificuldade": 6,
    "code": 23,
    "tipo": ["psiquico", "gelo"],
    "evolução": None,
    "FF": None,
    "vida": 107,
    "atk": 21,
    "atk SP": 38,
    "def": 23,
    "def SP": 29,
    "velocidade": 25,
    "XP": 0,
    "custo": 2,
    "moves": 4,
    "Tamanho": 1.5,
    "movelist": ["Cristalizar", "Reinado de Gelo", "Magia de Gelo", "Bola Psíquica", "Mente Forte", "Tapa Especial"],
    "H": 1.34,
    "W": 38.8
}

Pinsir = {
    "nome": "Pinsir",
    "raridade": "Raro",
    "dificuldade": 6,
    "code": 24,
    "tipo": ["inseto"],
    "evolução": None,
    "FF": [Mega_Pinsir],
    "vida": 106,
    "atk": 50,
    "atk SP": 19,
    "def": 28,
    "def SP": 24,
    "velocidade": 25,
    "XP": 0,
    "custo": 2,
    "moves": 4,
    "Tamanho": 1.6,
    "movelist": ["Seda", "Mordida", "Tesoura X", "Arranhar", "Esbravejar", "Treinar"],
    "H": 1.55,
    "W": 53

}

Mewtwo = {
    "nome": "Mewtwo",
    "raridade": "Lendario",
    "dificuldade": 12,
    "code": 25,
    "tipo": ["psiquico"],
    "evolução": None,
    "FF": [Mega_Mewtwo_X, Mega_Mewtwo_Y],
    "vida": 177,
    "atk": 65,
    "atk SP": 82,
    "def": 52,
    "def SP": 52,
    "velocidade": 70,
    "XP": 0,
    "custo": 3,
    "moves": 4,
    "Tamanho": 1.9,
    "movelist": ["Teleporte", "Corrosão Psíquica", "Psicorte Duplo", "Ampliação Mental", "Mente Forte", "Cauda Violenta"],
    "H": 1.9,
    "W": 95
}

Articuno = {
    "nome": "Articuno",
    "raridade": "Lendario",
    "dificuldade": 12,
    "code": 26,
    "tipo": ["voador", "gelo"],
    "evolução": None,
    "FF": None,
    "vida": 179,
    "atk": 40,
    "atk SP": 57,
    "def": 58,
    "def SP": 70,
    "velocidade": 53,
    "XP": 0,
    "custo": 3,
    "moves": 4,
    "Tamanho": 2.1,
    "movelist": ["Raio de Gelo", "Reinado de Gelo", "Voar", "Ataque de Asa", "Provocar", "Gelo Verdadeiro"],
    "H": 1.83,
    "W": 73
}

Moltres = {
    "nome": "Moltres",
    "raridade": "Lendario",
    "dificuldade": 12,
    "code": 27,
    "tipo": ["voador", "fogo"],
    "evolução": None,
    "FF": None,
    "vida": 197,
    "atk": 48,
    "atk SP": 73,
    "def": 56,
    "def SP": 42,
    "velocidade": 53,
    "XP": 0,
    "custo": 3,
    "moves": 4,
    "Tamanho": 2.3,
    "movelist": ["Ondas de Calor", "Raio de Fogo", "Voar", "Investida Aérea", "Provocar", "Superaquecer"],
    "H": 1.98,
    "W": 81
}

Zapdos = {
    "nome": "Zapdos",
    "raridade": "Lendario",
    "dificuldade": 12,
    "code": 28,
    "tipo": ["voador", "eletrico"],
    "evolução": None,
    "FF": None,
    "vida": 174,
    "atk": 53,
    "atk SP": 72,
    "def": 40,
    "def SP": 57,
    "velocidade": 60,
    "XP": 0,
    "custo": 3,
    "moves": 4,
    "Tamanho": 1.9,
    "movelist": ["Tempestade de Raios", "Choque do Trovão", "Voar", "Rasante", "Bola Elétrica", "Bico Broca"],
    "H": 1.72,
    "W": 69
}

Pokemons_Todos = [0,
    Bulbasaur, Charmander, Squirtle, Machop, Gastly, Geodude, Caterpie, Abra, Dratini, Pikachu,
    Zorua, Magikarp, Jigglypuff, Clefairy, Meowth, Cubone, Shellder, Magnemite, Rattata, Weedle, Snorlax, Aerodactyl, Jynx, Pinsir, Mewtwo, Articuno,Moltres,Zapdos]